- name: "Common Roles"
  hosts: all
  roles:
    - role: docker
      tags:
        - docker
    - role: java
      tags:
        - java

- name: "install python3-full for pip installing"
  hosts: all
  roles:
    - role: python3
      tags:
        - python3

- name: "Get git release"
  hosts: all
  tags:
    - ghr
  tasks:
    - name: Get latest release of a public repository
      community.general.github_release:
        user: ansible
        repo: ansible
        action: latest_release

