Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  # Vagrant ゲスト OS 同士で ssh するので。
  config.ssh.insert_key = false

  # disable default synced_folder
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "server01" do |machine|
    machine.vm.hostname = "server01.devel.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.6"
  end

  config.vm.define "server02" do |machine|
    machine.vm.hostname = "server02.devel.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.8"
  end

  config.vm.define "server03" do |machine|
    machine.vm.hostname = "server03.devel.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.9"
  end

  config.vm.define "deploy", primary: true do |machine|
    machine.vm.hostname = "deploy.devel.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.7"

    config.vm.synced_folder "../../playbook", "/vagrant",
                            type: "nfs",
                            id: "ansible",
                            mount_options: ["dmode=775,fmode=664"]
  end
end
