Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.synced_folder "../../playbook", "/vagrant", type: "rsync"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "vagrant.yml"
  end

  config.vm.define "devel01" do |machine|
    machine.vm.hostname = "devel01.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.7"
  end

  config.vm.define "devel02" do |machine|
    machine.vm.hostname = "devel02.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.8"
  end

  config.vm.define "devel03" do |machine|
    machine.vm.hostname = "devel03.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.9"
  end

  config.vm.define "devel04", primary: true do |machine|
    machine.vm.hostname = "devel04.ndxbn.tokyo"
    machine.vm.network :private_network, ip: "192.168.57.10"

    machine.vm.provision :file, source: "~/.ssh", destination: ".ssh"
    machine.vm.provision :shell, privileged: false,
                         inline: "chmod 600 ~/.ssh/*"
  end
end
