Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
    v.cpus = 2
    v.memory = 8 * 1024
  end
  config.vm.hostname = "ndxbn.local"
  config.vm.network "private_network", ip: "192.168.56.17"
  config.disksize.size = "100GB"

  # Provisioning
  config.vm.synced_folder "../../playbook", "/vagrant",
                          id: "ansible",
                          mount_options: ["dmode=775,fmode=664"]
  ## bootstrapping
  config.vm.provision :ansible_local,
                      playbook: "vagrant.yml"
end
